method_name: mmpose_3d
videos_dir: ../../videos/single_camera
models_dir: ./models
runs_dir: ./runs

arm_len_ref_m: 0.249

single_camera:
  device: cpu
  stride: 1
  max_frames: 0
  bbox_thr: 0.3
  kpt_thr: 0.3
  num_instances: 1
  rebase_keypoint_height: true

model:
  pose3d_alias: human3d

run_names:
  baseline: run
