method_name: media_pipe
videos_dir: ../../videos/single_camera
models_dir: ./models
runs_dir: ./runs

arm_len_ref_m: 0.249

single_camera:
  delegate: CPU
  running_mode: VIDEO
  stride: 1
  max_frames: 0
  num_poses: 1
  min_pose_detection_confidence: 0.5
  min_pose_presence_confidence: 0.5
  min_tracking_confidence: 0.5
  occlusion_thr: 0.5

run_names:
  baseline: run
  optimized: run_opt

optimized:
  keep_landmarks:
    - left_shoulder
    - right_shoulder
    - left_hip
    - right_hip
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_thumb
    - right_thumb
    - left_index
    - right_index
    - left_pinky
    - right_pinky
